{{- $fullName := include "wg-access-server.fullname" . -}}
{{- if .Values.wireguard.config.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}"
  labels:
    {{- include "wg-access-server.labels" . | nindent 4 }}
type: Opaque
data:
  privateKey: {{ .Values.wireguard.config.privateKey | b64enc | quote }}
  {{- if .Values.web.config.adminUsername }}
  adminUsername: {{ .Values.web.config.adminUsername | b64enc | quote }}
  {{- end }}
  adminPassword: {{ (include "wg-access-server.adminPassword" .) | b64enc | quote }}
{{- end }}
