site_name: wg-access-server
strict: true
repo_name: freifunkMUC/wg-access-server
repo_url: https://github.com/freifunkMUC/wg-access-server
site_url: https://www.freie-netze.org/wg-access-server/

theme:
  name: material
  include_sidebar: true
  icon:
    logo: material/cloud-outline # alias: cloud-queue
  palette:
    primary: light blue
    accent: teal

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - markdown_include.include:
      base_path: docs
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: " Â¶"

plugins:
  - search
